/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author caio.alunos
 */
public class FrmCidades extends javax.swing.JFrame {

    /**
     * Creates new form FrmCidades
     */
    public FrmCidades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbestado = new javax.swing.JComboBox<>();
        cbcidade = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        btnver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 221, 234));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estado ");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecionando UF e Cidade");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cidade");

        cbestado.setBackground(new java.awt.Color(255, 255, 255));
        cbestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbestado.setBorder(null);
        cbestado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbestadoActionPerformed(evt);
            }
        });

        cbcidade.setBackground(new java.awt.Color(255, 255, 255));
        cbcidade.setBorder(null);

        txtarea.setBackground(new java.awt.Color(255, 255, 255));
        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtarea.setRows(5);
        txtarea.setBorder(null);
        jScrollPane1.setViewportView(txtarea);

        btnver.setBackground(new java.awt.Color(255, 153, 204));
        btnver.setForeground(new java.awt.Color(255, 255, 255));
        btnver.setText("Ver");
        btnver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(cbestado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(36, 36, 36)
                                .addComponent(cbcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnver, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnver, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbestadoActionPerformed
        
        if(cbestado.getSelectedIndex() == 0){
            cbcidade.removeAllItems();
            cbcidade.addItem("Rio Branco");
            cbcidade.addItem("Cruzeiro do Sul"); 
            cbcidade.addItem("Sena Madureira");
        }
        
        else if (cbestado.getSelectedIndex() == 0) { // Acre
            cbcidade.removeAllItems();
            cbcidade.addItem("Rio Branco");
            cbcidade.addItem("Cruzeiro do Sul");
            cbcidade.addItem("Sena Madureira");
        } else if (cbestado.getSelectedIndex() == 1) { // Alagoas
            cbcidade.removeAllItems();
            cbcidade.addItem("Maceió");
            cbcidade.addItem("Arapiraca");
            cbcidade.addItem("Palmeira dos Índios");
        } else if (cbestado.getSelectedIndex() == 2) { // Amapá
            cbcidade.removeAllItems();
            cbcidade.addItem("Macapá");
            cbcidade.addItem("Santana");
            cbcidade.addItem("Laranjal do Jari");
        } else if (cbestado.getSelectedIndex() == 3) { // Amazonas
            cbcidade.removeAllItems();
            cbcidade.addItem("Manaus");
            cbcidade.addItem("Parintins");
            cbcidade.addItem("Itacoatiara");
        } else if (cbestado.getSelectedIndex() == 4) { // Bahia
            cbcidade.removeAllItems();
            cbcidade.addItem("Salvador");
            cbcidade.addItem("Feira de Santana");
            cbcidade.addItem("Vitória da Conquista");
        } else if (cbestado.getSelectedIndex() == 5) { // Ceará
            cbcidade.removeAllItems();
            cbcidade.addItem("Fortaleza");
            cbcidade.addItem("Caucaia");
            cbcidade.addItem("Juazeiro do Norte");
        } else if (cbestado.getSelectedIndex() == 6) { // Distrito Federal
            cbcidade.removeAllItems();
            cbcidade.addItem("Brasília");
            cbcidade.addItem("Ceilândia");
            cbcidade.addItem("Taguatinga");
        } else if (cbestado.getSelectedIndex() == 7) { // Espírito Santo
            cbcidade.removeAllItems();
            cbcidade.addItem("Vitória");
            cbcidade.addItem("Vila Velha");
            cbcidade.addItem("Cariacica");
        } else if (cbestado.getSelectedIndex() == 8) { // Goiás
            cbcidade.removeAllItems();
            cbcidade.addItem("Goiânia");
            cbcidade.addItem("Aparecida de Goiânia");
            cbcidade.addItem("Anápolis");
        } else if (cbestado.getSelectedIndex() == 9) { // Maranhão
            cbcidade.removeAllItems();
            cbcidade.addItem("São Luís");
            cbcidade.addItem("Imperatriz");
            cbcidade.addItem("Timon");
        } else if (cbestado.getSelectedIndex() == 10) { // Mato Grosso
            cbcidade.removeAllItems();
            cbcidade.addItem("Cuiabá");
            cbcidade.addItem("Várzea Grande");
            cbcidade.addItem("Rondonópolis");
        } else if (cbestado.getSelectedIndex() == 11) { // Mato Grosso do Sul
            cbcidade.removeAllItems();
            cbcidade.addItem("Campo Grande");
            cbcidade.addItem("Dourados");
            cbcidade.addItem("Três Lagoas");
        } else if (cbestado.getSelectedIndex() == 12) { // Minas Gerais
            cbcidade.removeAllItems();
            cbcidade.addItem("Belo Horizonte");
            cbcidade.addItem("Uberlândia");
            cbcidade.addItem("Contagem");
        } else if (cbestado.getSelectedIndex() == 13) { // Pará
            cbcidade.removeAllItems();
            cbcidade.addItem("Belém");
            cbcidade.addItem("Ananindeua");
            cbcidade.addItem("Santarém");
        } else if (cbestado.getSelectedIndex() == 14) { // Paraíba
            cbcidade.removeAllItems();
            cbcidade.addItem("João Pessoa");
            cbcidade.addItem("Campina Grande");
            cbcidade.addItem("Santa Rita");
        } else if (cbestado.getSelectedIndex() == 15) { // Paraná
            cbcidade.removeAllItems();
            cbcidade.addItem("Curitiba");
            cbcidade.addItem("Londrina");
            cbcidade.addItem("Maringá");
        } else if (cbestado.getSelectedIndex() == 16) { // Pernambuco
            cbcidade.removeAllItems();
            cbcidade.addItem("Recife");
            cbcidade.addItem("Jaboatão dos Guararapes");
            cbcidade.addItem("Olinda");
        } else if (cbestado.getSelectedIndex() == 17) { // Piauí
            cbcidade.removeAllItems();
            cbcidade.addItem("Teresina");
            cbcidade.addItem("Parnaíba");
            cbcidade.addItem("Picos");
        } else if (cbestado.getSelectedIndex() == 18) { // Rio de Janeiro
            cbcidade.removeAllItems();
            cbcidade.addItem("Rio de Janeiro");
            cbcidade.addItem("São Gonçalo");
            cbcidade.addItem("Duque de Caxias");
        } else if (cbestado.getSelectedIndex() == 19) { // Rio Grande do Norte
            cbcidade.removeAllItems();
            cbcidade.addItem("Natal");
            cbcidade.addItem("Mossoró");
            cbcidade.addItem("Parnamirim");
        } else if (cbestado.getSelectedIndex() == 20) { // Rio Grande do Sul
            cbcidade.removeAllItems();
            cbcidade.addItem("Porto Alegre");
            cbcidade.addItem("Caxias do Sul");
            cbcidade.addItem("Pelotas");
        } else if (cbestado.getSelectedIndex() == 21) { // Rondônia
            cbcidade.removeAllItems();
            cbcidade.addItem("Porto Velho");
            cbcidade.addItem("Ji-Paraná");
            cbcidade.addItem("Ariquemes");
        } else if (cbestado.getSelectedIndex() == 22) { // Roraima
            cbcidade.removeAllItems();
            cbcidade.addItem("Boa Vista");
            cbcidade.addItem("Rorainópolis");
            cbcidade.addItem("Caracaraí");
        } else if (cbestado.getSelectedIndex() == 23) { // Santa Catarina
            cbcidade.removeAllItems();
            cbcidade.addItem("Florianópolis");
            cbcidade.addItem("Joinville");
            cbcidade.addItem("Blumenau");
        } else if (cbestado.getSelectedIndex() == 24) { // São Paulo
            cbcidade.removeAllItems();
            cbcidade.addItem("São Paulo");
            cbcidade.addItem("São Roque");
            cbcidade.addItem("Itapevi");
        }

    }//GEN-LAST:event_cbestadoActionPerformed

    private void btnverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverActionPerformed
        txtarea.append("Estado escolhido: " + cbestado.getSelectedItem()+"\nCidade escolhida: "+cbcidade.getSelectedItem());
    }//GEN-LAST:event_btnverActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnver;
    private javax.swing.JComboBox<String> cbcidade;
    private javax.swing.JComboBox<String> cbestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
